### DISCUSSION TITLE
[Bug]: Remote admin not working on secondary channel

### DISCUSSION THREAD

**Discussion by kr4600** [meshtastic/firmware#7072] [Troubleshooting]
### Category

Other

### Hardware

T-Echo

### Is this bug report about any UI component firmware like InkHUD or Meshtatic UI (MUI)?

- [ ] Meshtastic UI aka MUI colorTFT
- [ ] InkHUD ePaper
- [ ] OLED slide UI on any display

### Firmware Version

2.6.11.60ec05e

### Description

I'm trying to create following setup:
Main radio
- Primary channel: private communication
- Secondary: backup communication for range extending clients

Range extender clients
- Primary: backup communication for range extending clients

From my tests it appears that common primary channel is required in order to establish remote admin connection.
From what I understand, this is not the desired effect. I have looked through the documentation, the definition of protobuf, and found no mention of this behavior. It seems to me that the remote admin should work with all devices that appear in the nodes tab, that is, all with which we can communicate. Am I thinking correctly?

My setup:
- T-Echo -> Meshtastic app; 2.6.6 (1457) iOS
- T-Echo -> Meshtastic web app; cli 2.6.3 MacOS

### Relevant log output

```Shell

```

**Comment by b8b8** [comment]
Make sure all nodes are on physically the same frequency and preset. Changing the private primary channels changes the frequency slot off default.

Then:

1. Add master node public key to slave node
2. Remove slave node from master node nodelist.
3. Send message on shared channel to force rediscovery of slave node.
4. Once rediscovered (green lock) exchanged keys, DM slave node from master node. Wait for explicit ack.
5. DM slave node from master node again, wait for ack.
6. Try and remote admin slave node.

**Reply by kr4600** [reply]
I went through your list two times and still couldn't use remote admin.
I double checked everything:
- Lora channel is hardcoded (although on 868 there's only one),
- Frequency is the same (868 eu),
- Preset is the same (long fast),
- Master's public key is present in slave's config (`--set security.adminKey base64:7T5[...]`)
- Messages pass in both channels and dm's - there's established connection
- On dm's theres green lock
- All messages has ack - only 2 nodes are up, ack must come from the other one, not from some other node which happen to retransmit it faster

Between attempts both nodes has their nodedb reset.

---
Below are partially redacted configs created using `meshtastic --export-config`
**Master**
```yaml
config:
  lora:
    channelNum: 1
    hopLimit: 3
    ignoreMqtt: true
    region: EU_868
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 27
    usePreset: true
  security:
    adminKey:
    - 'base64:'
    - 'base64:'
    - 'base64:'
    privateKey: base64:EuW[...]
    publicKey: base64:7T5[...]
    serialEnabled: true
owner: Master
owner_short: M
```

**Slave**
```yaml
config:
  lora:
    channelNum: 1
    hopLimit: 3
    ignoreMqtt: true
    region: EU_868
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 27
    usePreset: true
  security:
    adminKey:
    - base64:7T5[...]
    privateKey: base64:uIk[...]
    publicKey: base64:LT2[...]
    serialEnabled: true
owner: Slave
owner_short: S
```

I've also rawly went through iOS app logs but didn't find nothing connected to failed remote admin request but maybe i missed something.
