### ISSUE TITLE
[Feature Request]: MQTT downlink without LoRa Tx and uplink local node only

### ISSUE THREAD

**Issue by milkpirate** [meshtastic/firmware#3138]
### Category

Other

### Hardware

Heltec V3

### Firmware Version

v2.2.17.dbac2b1

### Description

My minimal setup looks like so:

```mermaid
graph LR
    PC <-->|Serial| NodeA
    <--> |LORA| NodeB
    <--> |Bluetooth| Android

    NodeA <--> |MQTT| mosquitto
```

the `mosquitto` log looks like so (converted to YAML for better readability):

```yaml
---
# lora/2/json/home-prim/!NodeA
channel: 0
from: 145556388
id: 1057405219
payload:
  air_util_tx: 0.125111117959023
  battery_level: 101
  channel_utilization: 0
  voltage: 4.35400009155273
sender: '!NodeA'
timestamp: 1706448997
to: 4294967295
type: telemetry
```
Messages sent from `Android` to `NodeB` in the prim. channel, look like so:
```yaml
---
# lora/2/json/home-secd/!NodeA
channel: 1
from: 3806671628
id: 1421562879
payload:
  text: test-message
rssi: -60
sender: '!NodeA'
snr: 13.5
timestamp: 1706449977
to: 4294967295
type: text
```
**1. Problem**: The message sent from `NodeB` does not appear as beeing sent from `NodeB` instead from `NodeA`.

When I send a message in the "private" channel from `NodeB` to `NodeA`, the message appears as:
```yaml
---
# lora/2/json/home-prim/!NodeA
channel: 0
from: 145556388
id: 1057405208
sender: '!NodeA'
timestamp: 1706448349
to: 3806671628
type: ""
```
**2. Problem**:
- The message type is empty
- There is no text at all
- And the source (sender) is not `NodeB` 

Is that as intended? Since to me it does not seem to be desirable.
