### ISSUE TITLE
[Bug]: Store and Forward breaks tapbacks

### ISSUE THREAD

**Issue by k1n6b0b** [meshtastic/firmware#5578]
### Category

Hardware Compatibility

### Hardware

T-Beam

### Firmware Version

2.5.15

### Description

With 

```
  storeForward:
    enabled: true
    heartbeat: true
    isServer: true
```

tapbacks do not show on the message (see below)
![image](https://github.com/user-attachments/assets/1226d0d9-b471-4cd5-95fa-49099f557426)
