### ISSUE TITLE
[Feature Request]: Add VFS location to Native config.yaml

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/firmware#5775]
### Platform

Linux Native

### Description

As I experiment with running multiple native instances, it occurs that it may be useful to allow configuration of API port and Virtual File System in the config.yaml. 

Currently they are configurable by using flags eg:
```
./meshtasticd_linux_aarch64 -d /home/pdxlocs/.portduino/vfs4 -p 4406
```

A suggestion for how they could be added:
```
General:
  MaxNodes: 200
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
  VFSDirectory: ~/.portduino/default/   # The directory to use as the virtual file system
  APIPort: 4403                         # The local TCP port to use for running the Meshtastic API
#  MACAddress: AA:BB:CC:DD:EE:FF
#  MACAddressSource: eth0
```
