### ISSUE TITLE
[Bug]: config.d yaml overwrites all key's values in config.yaml

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/firmware#6102]
### Category

Other

### Hardware

Linux Native

### Firmware Version

2.5.21

### Description

Yaml keys in config categories may overwrite the entire category, while the intention is to merge them.
Discord discussion here: https://discord.com/channels/867578229534359593/972586878337433670/1341855284728958977

with `/etc/meshtasticd/config.yaml` including:
```
General:
  MaxNodes: 500
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
#  MACAddress: AA:BB:CC:DD:EE:FF
#  MACAddressSource: eth0
```

and `/etc/meshtasticd/config.d/test.yaml` including:
```
General:
  MaxMessageQueue: 100
```

The nodedb size does not honor settings from config.yaml and defaults to 200:

```
Feb 19 13:34:43 meshdev meshtasticd[73564]: INFO  | 21:34:41 4093 [Router] Node database full with 200 nodes and 4294967295 bytes free. Erasing oldest entry
Feb 19 13:34:43 meshdev meshtasticd[73564]: INFO  | 21:34:41 4093 [Router] Adding node to database with 200 nodes and 4294967295 bytes free!
```

delete test.yaml and the nodedb size may again exceed the default 200:

```
Feb 19 14:14:24 meshdev meshtasticd[74851]: INFO  | 22:14:03 1194 [Router] Adding node to database with 202 nodes and 4294967295 bytes free!
```
