### ISSUE TITLE
[Bug]: RAK4631 doesn't do TLS over Ethernet

### ISSUE THREAD

**Issue by kstrauser** [meshtastic/firmware#6282]
### Category

Other

### Hardware

Rak4631

### Firmware Version

2.5.20.4c97351

### Description

I have a RAK4631 radio with RAK13800 Ethernet. I also have an MQTT server that supports both plaintext (port 1883) and TLS (port 8883) connections.

Regardless of the value of `mqtt.tls_enabled`, the radio always connects to the server's plaintext port 1883. I would've expected to connect to TLS port 8883.

### Relevant log output

```Shell

```

**Comment by garthvh** [comment]
There is no web server on a NRF board, I am pretty sure ssl is not supported.

**Comment by kstrauser** [comment]
Is TLS only compiled in if the board has a web server?

**Comment by kstrauser** [comment]
That's exactly it, @randshell. I've configured the radio to connect to the MQTT server with TLS, but it's silently downgraded to plaintext.

Also, the server is "local" in the "not the default shared server" sense. It has TLS configured with a legit signed certificate. For testing just now, I changed its MQTT config to:

```
  mqtt:
    address: mqtt.meshtastic.org
    enabled: true
    encryptionEnabled: true
    mapReportSettings:
      positionPrecision: 32
    mapReportingEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
    tlsEnabled: true
```

After the reboot, here's what that connection looks like in my logs:

```
INFO  | ??:??:?? 10 [mqtt] Connect directly to MQTT server mqtt.meshtastic.org, port: 1883, username: meshdev, password: large4cats
```

So even with the default public server, `tlsEnabled` is ignored. I agree that I'd rather see an error message than it silently downgrading to plaintext.
