### ISSUE TITLE
[Bug]: Meshtasticd doesn't start. Assertion `n < NUM_GPIOS' failed

### ISSUE THREAD

**Issue by qkdxorjs1002** [meshtastic/firmware#6304]
### Category

Hardware Compatibility

### Hardware

Linux Native

### Firmware Version

2.6.1.9~obs7c3edde~

### Description

When I tried to set up and start meshtasticd on Raspberry Pi, I was experiencing the following error.
If I set DIO3_TCXO_VOLTAGE, an error appears. If I don't set it, meshtastic can't detect the module with -707 error.
The module rx/tx signal is tested with my testing code and RTL-SDR.

**Hardware**
Host: Raspberry Pi CM5 Lite
OS: Raspbian 12 Bookworm (6.12.x)
Module: E22-900M22S
Interface: SPI (on RPi CM5 SPI1-CE0)
Region: KR (920MHZ-923MHz)

**Configuration**
```yaml
Logging:
  LogLevel: debug
Lora:
  Module: sx1262
  DIO3_TCXO_VOLTAGE: 1.8
  SX126X_MAX_POWER: 22
  gpiochip: 4
  spidev: spidev1.0
#  CS: 18
  Reset: 14
  Busy: 15
```

### Relevant log output

```Shell
3월 13 10:44:02 uconsole systemd[1]: Started meshtasticd.service - Meshtastic Native Daemon.
 3월 13 10:44:02 uconsole meshtasticd[8834]: Portduino is starting, VFS root at /root/.portduino/default
 3월 13 10:44:02 uconsole meshtasticd[8834]: Set up Meshtastic on Portduino...
 3월 13 10:44:02 uconsole meshtasticd[8834]: Using /etc/meshtasticd/config.yaml as config file
 3월 13 10:44:02 uconsole meshtasticd[8834]: Also using "/etc/meshtasticd/config.d/lora-ebyte-e22-900m22s.yaml" as additional config file
 3월 13 10:44:02 uconsole meshtasticd[8834]: meshtasticd: pio/packages/framework-portduino/cores/portduino/PortduinoGPIO.cpp:48: GPIOPinIf* getGPIO(pin_size_t): Assertion `n < NUM_GPIOS' failed.
 3월 13 10:44:02 uconsole systemd[1]: meshtasticd.service: Main process exited, code=killed, status=6/ABRT
 3월 13 10:44:02 uconsole systemd[1]: meshtasticd.service: Failed with result 'signal'.
```

**Comment by GPSFan** [comment]
I have had a similar problem with my LuckFox pico mini since 2.5.19. I wound up digging into RadioLib and patching 126x.cpp in modSetup to remove state = reset(), state = standby and their associated ASSERTs. This is because the findChip() code already does a reset and I believe that doing 2 resets so close together causes the SX1262 some problems. 
There are comments in the code indication that after a reset() the SX1262 doesn't respond to commands for a while and they supposedly take steps to address this. However in ther modSetup code the comment just before the reset says:
  // reset the module and verify startup

Yet the reset() invocation isn't reset(true) so it won't verify the SX1262 is ok before returning. 
I tried a reset(true and it didn't make any difference, but removing the reset() and standby() fixed the problem.

I don't know if this is the right solution, but it worked for me on each new meshtasticd release since.

**Comment by qkdxorjs1002** [comment]
In SX126x constructor, parameters are -1 when value is not set.
I guessed that essential pin assertion this caused an error.
So I solved it by setting up an IRQ pin that was not actually assigned.

```
Logging:
  LogLevel: debug
Lora:
  Module: sx1262
  DIO2_AS_RF_SWITCH: true
  DIO3_TCXO_VOLTAGE: 1.8
  gpiochip: 4
  spidev: spidev1.0
  spiSpeed: 8000000
#  CS: 18
  IRQ: 17
  Reset: 14
  Busy: 15
```
