### ISSUE TITLE
[Bug]: Enabling the Alert Message/Bell LED settings also enables the Buzzer, even when the Alert Message/Bell Buzzer is switched off.

### ISSUE THREAD

**Issue by Supermath101** [meshtastic/firmware#6368]
### Category

Other

### Hardware

Seeed Card Tracker T1000-E

### Firmware Version

2.6.1.7c3edde

### Description

With the External Notification module enabled, if I enabled the LED alert settings, it also enables the Buzzer, even when the Buzzer alert setting is set to disabled. This bug occurs for both the Alert message LED/buzzer and Alert bell LED/buzzer setting pairs.

### Relevant log output

```Shell

```

**Comment by fifieldt** [comment]
Looks like the code may just check if the buzzer GPIO is defined rather than if it's enabled. Easy fix, will test.

`
        // now let the PWM buzzer play
        if (moduleConfig.external_notification.use_pwm && config.device.buzzer_gpio) {
            if (rtttl::isPlaying()) {
                rtttl::play();
            } else if (isNagging && (nagCycleCutoff >= millis())) {
                // start the song again if we have time left
                rtttl::begin(config.device.buzzer_gpio, rtttlConfig.ringtone);
            }
        }
`

**Comment by fifieldt** [comment]
hmm, use_pwm is probably the right value.

defaults:
```
 690 #if defined(PIN_BUZZER)
 691     moduleConfig.external_notification.enabled = true;
 692     moduleConfig.external_notification.output_buzzer = PIN_BUZZER;
 693     moduleConfig.external_notification.use_pwm = true;
 694     moduleConfig.external_notification.alert_message_buzzer = true;
 695     moduleConfig.external_notification.nag_timeout = 60;
 696 #endif

**Comment by fifieldt** [comment]
With Alert message LED only, no buzzer sounds (2.6.2)

![Image](https://github.com/user-attachments/assets/a28f6d7d-ae3e-45da-b61e-82f190050e60)

**Comment by fifieldt** [comment]
With both Alert Message LED and Alert Bell LED enabled, no buzzer sounds. 

![Image](https://github.com/user-attachments/assets/9626a8fa-1483-4474-9cb9-71f8937391bd)

**Comment by fifieldt** [comment]
Unfortunately, I can't reproduce this - are you able to export your settings and upload, or take a screenshot of the external notification page?

and, just to confirm - you're not talking about the startup/shutdown buzzer?

**Comment by fifieldt** [comment]
Apologies, I just realised I was running 2.5.22, not 2.6.2

**Comment by Supermath101** [comment]
> Unfortunately, I can't reproduce this - are you able to export your settings and upload, or take a screenshot of the external notification page?
> 
> and, just to confirm - you're not talking about the startup/shutdown buzzer?

I'm *not* talking about the startup/shutdown buzzer. Here's my config:
```yml
# start of Meshtastic configure yaml
channel_url: REDACTED
config:
  bluetooth:
    enabled: true
    fixedPin: REDACTED
    mode: FIXED_PIN
  device:
    buzzerGpio: 25
    disableTripleClick: true
    ledHeartbeatDisabled: true
    nodeInfoBroadcastSecs: 10800
    role: CLIENT_MUTE
    tzdef: EST5EDT,M3.2.0,M11.1.0
  display:
    screenOnSecs: 600
    units: IMPERIAL
  lora:
    hopLimit: 5
    ignoreMqtt: true
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    gpsEnGpio: 43
    gpsMode: ENABLED
    gpsUpdateInterval: 15
    positionBroadcastSecs: 900
    positionBroadcastSmartEnabled: true
    positionFlags: 811
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: REDACTED
    publicKey: base64:n71jei/uNpIqJdRZ4ZF5fVdjUOJ8adaFjQKrqOiZfhY=
    serialEnabled: true
location:
  alt: REDACTED
  lat: REDACTED
  lon: REDACTED
module_config:
  ambientLighting:
    blue: 125
    current: 10
    green: 161
    red: 205
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  externalNotification:
    active: true
    alertMessage: true
    enabled: true
    nagTimeout: 1
    output: 24
    outputBuzzer: 25
    usePwm: true
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
  rangeTest:
    enabled: true
owner: Supermath101 (a17d)
owner_short: a17d
```
